package config

import (
	"strings"
	"testing"

	"hf2s3/pkg/crypto"
)

func env(m map[string]string) Getenv {
	return func(k string) string { return m[k] }
}

func goodMasterKey(t *testing.T) string {
	t.Helper()
	k, err := crypto.GenerateMasterKey()
	if err != nil {
		t.Fatal(err)
	}
	return k
}

func TestFromEnvironmentDefaultsAndPrecedenceMarkers(t *testing.T) {
	c, err := FromEnvironment(env(map[string]string{
		"HF2S3_ACCESS_KEY": "AKIAEXAMPLEKEY01", "HF2S3_SECRET_KEY": strings.Repeat("s", 32),
		"ADMIN_USERNAME": "root", "ADMIN_PASSWORD": "a-long-admin-password",
		"HF2S3_CHUNK_SIZE_MB": "64", "PORT": "9000",
		"HF2S3_CORS_ORIGINS": "https://a.example, https://b.example", "HF2S3_LEGACY_MASTER_KEYS": "old1,old2",
	}))
	if err != nil {
		t.Fatal(err)
	}
	if c.Port != 9000 || c.ChunkSizeMB != 64 || c.RedirectMode != "auto" || c.LogFormat != "json" || c.Region != "us-east-1" {
		t.Fatalf("unexpected values: %+v", c)
	}
	for _, k := range []string{"access_key_id", "secret_access_key", "admin_username", "admin_password", "chunk_size_mb"} {
		if !c.FromEnv[k] {
			t.Errorf("%s should be marked as environment-managed", k)
		}
	}
	if c.FromEnv["s3_region"] {
		t.Error("an unset variable must not be marked as managed")
	}
	if len(c.CORSOrigins) != 2 || len(c.LegacyMasterKeys) != 2 {
		t.Fatalf("list parsing: %v %v", c.CORSOrigins, c.LegacyMasterKeys)
	}
}

func TestFromEnvironmentRejectsBadNumbers(t *testing.T) {
	if _, err := FromEnvironment(env(map[string]string{"PORT": "eighty"})); err == nil {
		t.Fatal("non-numeric PORT must fail")
	}
}

func TestValidateRequiresStrongMasterKeyInProduction(t *testing.T) {
	base := map[string]string{}
	c, _ := FromEnvironment(env(base))
	if err := c.Validate(); err == nil || !strings.Contains(err.Error(), "HF2S3_MASTER_KEY is required") {
		t.Fatalf("missing master key must be refused: %v", err)
	}

	base["HF2S3_MASTER_KEY"] = "hf2s3-aes-master-passphrase-2026"
	c, _ = FromEnvironment(env(base))
	if err := c.Validate(); err == nil {
		t.Fatal("the old default passphrase must not be accepted as master key")
	}

	base["HF2S3_MASTER_KEY"] = goodMasterKey(t)
	c, _ = FromEnvironment(env(base))
	if err := c.Validate(); err != nil {
		t.Fatalf("a generated master key must be accepted: %v", err)
	}

	// Dev mode tolerates a missing key (an ephemeral one is generated by the caller).
	dev, _ := FromEnvironment(env(map[string]string{"HF2S3_DEV": "1"}))
	if err := dev.Validate(); err != nil {
		t.Fatalf("dev mode: %v", err)
	}
}

func TestValidateRejectsBadOptions(t *testing.T) {
	c, _ := FromEnvironment(env(map[string]string{
		"HF2S3_MASTER_KEY": goodMasterKey(t), "S3_GET_REDIRECT": "sometimes", "HF2S3_PUBLIC_URL": "not a url",
		"HF2S3_CHUNK_SIZE_MB": "9999", "HF2S3_LOG_FORMAT": "xml",
	}))
	err := c.Validate()
	if err == nil {
		t.Fatal("expected validation errors")
	}
	for _, want := range []string{"S3_GET_REDIRECT", "HF2S3_PUBLIC_URL", "HF2S3_CHUNK_SIZE_MB", "HF2S3_LOG_FORMAT"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error should mention %s: %v", want, err)
		}
	}
}

func TestCheckCredentials(t *testing.T) {
	good := func() error {
		return CheckCredentials(false, "AKIAEXAMPLEKEY01", strings.Repeat("k", 32), "root", false, "a-long-admin-password")
	}
	if err := good(); err != nil {
		t.Fatalf("strong credentials refused: %v", err)
	}

	cases := map[string]func() error{
		"default access key": func() error {
			return CheckCredentials(false, "hf2s3-access-key", strings.Repeat("k", 32), "root", false, "a-long-admin-password")
		},
		"default secret": func() error {
			return CheckCredentials(false, "AKIAEXAMPLEKEY01", "hf2s3-secret-key", "root", false, "a-long-admin-password")
		},
		"short secret": func() error {
			return CheckCredentials(false, "AKIAEXAMPLEKEY01", "short", "root", false, "a-long-admin-password")
		},
		"default admin pass": func() error {
			return CheckCredentials(false, "AKIAEXAMPLEKEY01", strings.Repeat("k", 32), "admin", false, "admin123")
		},
		"short admin pass": func() error {
			return CheckCredentials(false, "AKIAEXAMPLEKEY01", strings.Repeat("k", 32), "root", false, "short")
		},
		"empty everything": func() error { return CheckCredentials(false, "", "", "", false, "") },
	}
	for name, f := range cases {
		if err := f(); err == nil {
			t.Errorf("%s must be refused in production", name)
		}
	}

	// A stored password hash is accepted as-is; dev mode skips the checks.
	if err := CheckCredentials(false, "AKIAEXAMPLEKEY01", strings.Repeat("k", 32), "root", true, "pbkdf2-sha256$1$x$y"); err != nil {
		t.Fatalf("stored hash refused: %v", err)
	}
	if err := CheckCredentials(true, "", "", "", false, ""); err != nil {
		t.Fatalf("dev mode must not enforce: %v", err)
	}
}

func TestIsWeak(t *testing.T) {
	for _, v := range []string{"", "ADMIN123", "hf2s3-secret-key"} {
		if !IsWeak(v, 0) {
			t.Errorf("%q should be weak (case-insensitive default match)", v)
		}
	}
	if IsWeak("Zx9-unique-and-long-enough", 12) {
		t.Error("strong value flagged")
	}
}
